{% set name = "napari-dv" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bf7b0e00b0a5839718321e56c6bfeb8c0ed31aefa32b4e46909644b8d0bc963c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - mrc >=0.1.5
    - napari-plugin-engine >=0.1.4
    - python >={{ python_min }}

test:
  imports:
    - napari_dv
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tlambert03/napari-dv
  summary: Deltavision/MRC file reader for napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - tlambert03
